Explore page port
baseplate-admin/coreproject-v4-ui pull request #319
Opened 2024-08-01 12:19 UTC by meowsocute

`/anime/explore/` page ported to Svelte 5,
> added `loadsh-es` dependency.
> added `/types/anime.ts`, `/functions/get_csrf_token.ts`, `/functions/get_csrf_token.ts`.

2024-08-01 14:19 UTC, baseplate-admin requested changes
Overall a solid start

2024-08-01 14:19 UTC, baseplate-admin commented on package.json
> +		"@types/lodash-es": "^4.17.12",
We dont want lodash

2024-08-01 14:19 UTC, baseplate-admin commented on package.json
> +		"lodash-es": "^4.17.21",
these 2 are not needed?

2024-08-01 14:19 UTC, baseplate-admin commented on src/lib/components/anime_card.svelte
> +	import { enhance_anchor } from "$functions/anchor_enhancements";
This function wont work in svelte environment

2024-08-01 14:19 UTC, baseplate-admin commented on src/lib/components/anime_card.svelte
> +    export let anime_rating: string;
Neither of them are runes

2024-08-01 16:21 UTC, moonlitgrace reviewed
:standing_man:  :gun:

2024-08-01 16:21 UTC, moonlitgrace commented on src/lib/functions/anchor_enhancements.ts
this function is not needed for svelte

2024-08-01 16:21 UTC, moonlitgrace commented on src/lib/functions/get_csrf_token.ts
this too

2024-08-01 16:21 UTC, moonlitgrace commented on src/lib/functions/urls/goto.ts
this too

2024-08-01 16:21 UTC, moonlitgrace commented on src/lib/functions/urls/reverse.ts
and this too

2024-08-03 06:51 UTC, moonlitgrace requested changes

2024-08-03 06:51 UTC, moonlitgrace commented on src/routes/anime/+layout.svelte
> -			<div id="page" class="w-full overflow-y-scroll">
dont remove it here, btw it was working fine on firefox
maybe you try it on ff?

https://coreproject-v4-ebfwbikcy-baseplateadmins-projects.vercel.app/anime/mal/1/episode/1

2024-08-03 14:32 UTC, moonlitgrace commented on src/routes/anime/explore/+page.svelte
> +				url.searchParams.set(key, value);
```ts
url.searchParams.set(key, String(va));
```

and can you tell why you need to ensure if this a string? it is already not?

2024-09-27 01:59 UTC, moonlitgrace commented
Porting done on #477

2024-09-27 01:59 UTC, closed without merging