feat: support sveltekit-i18n
baseplate-admin/coreproject-v4-ui pull request #65
Opened 2024-05-18 17:39 UTC by tokitouq

Closes #44

2024-05-18 19:54 UTC, tokitouq commented on src/routes/+layout.server.ts
> +import type { Translations } from "../../node_modules/sveltekit-i18n/node_modules/@sveltekit-i18n/base";
I've made an issue regarding this:
https://github.com/sveltekit-i18n/lib/issues/181

2024-05-18 20:50 UTC, baseplate-admin commented
I have added some translation. Most of them sound like i am a 1st grader. Its a start. you make the switching logic, i will add more configs

2024-05-19 03:22 UTC, tokitouq commented
> Its a start. you make the switching logic, i will add more configs

Yea I will do that, also I will try to expose more keys.
I will update you, until then no work on this okay?

2024-05-19 04:32 UTC, tokitouq commented
@baseplate-admin what do you think bout adding other languages support later? I mean after testing with some langs?
Also I used AI to generate bengali translations, see if it looks good to you. if so we can use it :zap:

2024-05-19 09:23 UTC, baseplate-admin requested changes
This is unscalable. we want new translation backend @akindworld

2024-05-19 09:23 UTC, baseplate-admin commented on src/lib/translations/bn/home.json
> +		"explore": "অন্বেষণ",
অন্বেষণ -> খুঁজুন

2024-05-19 09:23 UTC, baseplate-admin commented on src/lib/translations/bn/home.json
> +		"forum": "ফোরাম",
ফোরাম -> মঞ্চ

2024-05-19 12:02 UTC, tokitouq commented on src/lib/translations/bn/home.json
> +		"explore": "অন্বেষণ",
Yea Idk bengali, well resolved suggested changes on https://github.com/baseplate-admin/coreproject-v4-ui/pull/65/commits/24f7dc4f44f71081edc4b4e90e6dc5def08ed6e2

2024-05-19 18:29 UTC, tokitouq commented
@baseplate-admin
The goal of this PR has achieved :tada: so Imma merge this for now.
lets work on translations on separate PR

2024-05-19 18:29 UTC, merged